spring:
  application:
    name: learn-graphql-java
  servlet:
    multipart:
      max-file-size: 2MB

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 100
    ##This is to enable the exception handling withing a graphql request
    exception-handlers-enabled: true
    tracingEnabled: false
  playground:
    headers:
      Authorization: Bearer TOKEN
      user_id: IDP|Philip
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
voyager:
  enabled: true

logging:
  pattern:
    #    This part %clr(%X{correlation_id}){red} was added to this property of the CONSOLE_LOG_PATTERN found in defaults.xml file to print the correlation id in red
    console: -%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%X{correlation_id}){red} %m%n%wEx
